title: portafolio practica 6
description: Esta va a ser un pagina web en la que voy a ir publicando y actualizando el transcurso del curso y entre otras cosas subiré los trabajos que vaya realizando y me gusten de cada asignatura.
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
